services:
  postgres:
    image: timescale/timescaledb:latest-pg17
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    network_mode: bridge
    
  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "3004:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
    network_mode: bridge

volumes:
  postgres-data:
  pgadmin-data:
